version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: vertcoind -conf=/data/vertcoin.conf
    volumes:
      - .:/data
    ports:
      - "5888:5888"
      - "5889:5889"
